development:
  adapter: mysql
  database: scm_development
  host: localhost
  username: root
  password: 
test:
  adapter: mysql
  database: scm_test
  host: localhost
  username: root
  password: 

sgc_production:
  adapter: mysql
  database: scm_sgcprod
  host: localhost
  username: root
  password: 
ci5_production:
  adapter: mysql
  database: scm_ci5prod
  host: localhost
  username: root
  password: 
hunter_production:
  adapter: mysql
  database: scm_hunterprod
  host: localhost
  username: root
  password: 
